export const Screens= {
    // App Navigation
    HOMESCREENS:'HomeScreens',
    ADDDATA:'ADDDATA',
    LOGIN:'LOGIN',
    SIGNUP:'SIGNUP',
    SPLASH:'SPLASH',
    DETAILSCREEN:'DETAILSCREEN',
    PROFILE:'PROFILE',
    SHIPING:'SHIPING',
    NOTIFICATION:"NOTIFICATION",
    ORDER:'ORDER',
    CART:'CART'
}